# netlify.toml for your Jekyll academicpages site

[build]
  # 构建命令
  command = "bundle exec jekyll build"
  # 构建完成后的发布目录
  publish = "_site"

[build.environment]
  # 设置环境变量
  JEKYLL_ENV = "production"
  RUBY_VERSION = "3.1.2" # 确保这个版本和你的 Gemfile 兼容
